"""PR creator — assembles pipeline output into a GitHub Pull Request.

No LLM calls. Pure Python + GitHub API.
"""

import json
import os
import shutil
from datetime import datetime, timezone
from pathlib import Path

from .config import KB_DIRS, STAGING_DIR


def generate_pr_body(
    drafts: list[dict],
    panel_results: list,
    crossref_suggestions: dict,
    spend_summary: str,
) -> str:
    """Generate a markdown PR body summarizing the pipeline run."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    sections = [
        f"## Weekly KB Update — {now}",
        "",
        "This PR was generated by the automated agent pipeline.",
        "**Human review required before merge.**",
        "",
    ]

    # Summary table
    approved = sum(1 for r in panel_results if r.consensus == "approve")
    revise = sum(1 for r in panel_results if r.consensus == "revise")
    rejected = sum(1 for r in panel_results if r.consensus == "reject")

    sections.append("### Pipeline Summary")
    sections.append(f"- Drafts created: {len(drafts)}")
    sections.append(f"- Panel approved: {approved}")
    sections.append(f"- Panel revise: {revise}")
    sections.append(f"- Panel rejected: {rejected}")
    sections.append("")

    # Draft details
    sections.append("### Entries")
    for draft, result in zip(drafts, panel_results):
        status_emoji = {
            "approve": "[APPROVED]",
            "revise": "[NEEDS REVISION]",
            "reject": "[REJECTED]",
        }
        sections.append(
            f"- {status_emoji.get(result.consensus, '?')} "
            f"`{draft.get('type', '?')}/{draft.get('filename', '?')}` "
            f"(from: {draft.get('_paper_title', 'Unknown')[:60]})"
        )

        # Show concerns if any
        for review in result.reviews:
            if review.concerns:
                for concern in review.concerns:
                    sections.append(f"  - {review.role}: {concern}")
    sections.append("")

    # Cross-reference suggestions
    total_xref = sum(
        len(s.get("add_to_existing", []))
        for s in crossref_suggestions.values()
    )
    if total_xref > 0:
        sections.append(f"### Cross-Reference Suggestions ({total_xref})")
        for filename, suggestions in crossref_suggestions.items():
            for s in suggestions.get("add_to_existing", []):
                sections.append(
                    f"- Add `[[{s['link']}]]` to `{s['entry']}` ({s['note']})"
                )
        sections.append("")

    # Spend
    sections.append("### Cost")
    sections.append(f"```\n{spend_summary}\n```")
    sections.append("")

    sections.append("---")
    sections.append(
        "*Review each entry, then merge approved entries into the KB. "
        "Rejected entries can be deleted from the staging directory.*"
    )

    return "\n".join(sections)


def prepare_pr_files(
    drafts: list[dict],
    panel_results: list,
) -> list[dict]:
    """Prepare file changes for the PR.

    Returns list of {path, content, action} dicts describing changes.
    Only includes approved entries — revise/reject stay in staging for
    manual review.
    """
    changes = []

    for draft, result in zip(drafts, panel_results):
        if result.consensus != "approve":
            continue

        entry_type = draft.get("type", "concept")
        filename = draft.get("filename", "")
        content = draft.get("content", "")

        if not filename or not content:
            continue

        # Target path in KB
        target_dir = KB_DIRS.get(f"{entry_type}s")  # concepts, frameworks, etc.
        if target_dir is None:
            target_dir = KB_DIRS.get(entry_type)  # try without plural
        if target_dir is None:
            continue

        target_path = target_dir / filename

        changes.append(
            {
                "path": str(target_path),
                "relative_path": f"{entry_type}s/{filename}",
                "content": content,
                "action": "update" if target_path.exists() else "create",
            }
        )

    return changes


def create_pr_local(
    drafts: list[dict],
    panel_results: list,
    crossref_suggestions: dict,
    spend_summary: str,
) -> dict:
    """Create PR materials locally (for non-GitHub environments).

    Returns a dict with pr_body and file changes.
    Used when running locally without GitHub API access.
    """
    body = generate_pr_body(
        drafts, panel_results, crossref_suggestions, spend_summary
    )
    changes = prepare_pr_files(drafts, panel_results)

    # Save PR body
    pr_path = STAGING_DIR / "pr-body.md"
    pr_path.write_text(body)

    # Save changes index
    changes_path = STAGING_DIR / "pr-changes.json"
    with open(str(changes_path), "w") as f:
        json.dump(changes, f, indent=2)

    return {"body": body, "changes": changes}


def create_pr_github(
    drafts: list[dict],
    panel_results: list,
    crossref_suggestions: dict,
    spend_summary: str,
    repo_name: str = "jarmolkowicz/modern-mind-knowledge-base",
    base_branch: str = "main",
) -> str | None:
    """Create an actual GitHub PR. Returns PR URL or None on failure."""
    try:
        from github import Github
    except ImportError:
        print("  [pr] PyGithub not available, falling back to local PR")
        create_pr_local(
            drafts, panel_results, crossref_suggestions, spend_summary
        )
        return None

    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("  [pr] No GITHUB_TOKEN, falling back to local PR")
        create_pr_local(
            drafts, panel_results, crossref_suggestions, spend_summary
        )
        return None

    changes = prepare_pr_files(drafts, panel_results)
    if not changes:
        print("  [pr] No approved entries to create PR for")
        return None

    g = Github(token)
    repo = g.get_repo(repo_name)

    # Create branch
    now = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M")
    branch_name = f"kb-update/{now}"

    main_ref = repo.get_git_ref(f"heads/{base_branch}")
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=main_ref.object.sha,
    )

    # Commit files
    for change in changes:
        repo.create_file(
            path=change["relative_path"],
            message=f"Add {change['relative_path']} via agent pipeline",
            content=change["content"],
            branch=branch_name,
        )

    # Create PR
    body = generate_pr_body(
        drafts, panel_results, crossref_suggestions, spend_summary
    )

    pr = repo.create_pull(
        title=f"KB Update — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
        body=body,
        head=branch_name,
        base=base_branch,
    )

    print(f"  [pr] Created PR: {pr.html_url}")
    return pr.html_url


def run(
    drafts: list[dict],
    panel_results: list,
    crossref_suggestions: dict,
    spend_summary: str,
) -> str | None:
    """Create a PR (GitHub if possible, local fallback)."""
    print("[pr] Preparing pull request...")

    if os.environ.get("GITHUB_TOKEN"):
        return create_pr_github(
            drafts, panel_results, crossref_suggestions, spend_summary
        )
    else:
        result = create_pr_local(
            drafts, panel_results, crossref_suggestions, spend_summary
        )
        print(f"[pr] Local PR materials saved to {STAGING_DIR}")
        return None
