"""Regenerate index.md from current KB entries.

Mechanical, deterministic. No LLM calls. Run via:

    python tooling/scripts/build-index.py

Output: index.md at the repo root, with one row per entry grouped by type.
For each entry, a short one-liner is extracted from the appropriate section
(Key Insight for sources, What It Is for concepts, Overview for methods).
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

# Allow running as a standalone script.
_DIR = Path(__file__).resolve().parent
if str(_DIR) not in sys.path:
    sys.path.insert(0, str(_DIR))

from kb_search import KB_ROOT, Entry, load_entries  # noqa: E402

INDEX_PATH = KB_ROOT / "index.md"

# Which section headers to extract a one-liner from, per entry type.
# First match wins.
SECTION_HEADERS_BY_TYPE: dict[str, list[str]] = {
    "source": ["Key Insight"],
    "concept": ["What It Is", "Overview"],
    "framework": ["Overview", "Core Idea", "What It Is"],
    "practice": ["What To Do", "Overview", "What It Is"],
    "method": ["Overview", "What It Is", "What To Do"],
}

# Display order for type sections in the index.
TYPE_ORDER = ["source", "concept", "method", "framework", "practice"]

TYPE_LABEL = {
    "source": "Sources",
    "concept": "Concepts",
    "method": "Methods",
    "framework": "Frameworks",
    "practice": "Practices",
}

ONELINER_MAX_CHARS = 140


def _extract_oneliner(body: str, section_headers: list[str]) -> str:
    """Find the first matching section header and return its first sentence."""
    for header in section_headers:
        pattern = rf"^##\s+{re.escape(header)}\s*\n+(.+?)(?=^##\s+|\Z)"
        m = re.search(pattern, body, re.MULTILINE | re.DOTALL)
        if not m:
            continue
        content = m.group(1).strip()
        # Skip leading bullet markers / quote markers if present
        content = re.sub(r"^[>\-*]\s*", "", content)
        # First sentence — split on ". ", "? ", "! " or end of paragraph
        sentence_match = re.match(r"(.+?[.!?])(?:\s|\n|$)", content, re.DOTALL)
        text = sentence_match.group(1) if sentence_match else content
        text = re.sub(r"\s+", " ", text).strip()
        # Escape pipe characters so they don't break the markdown table
        text = text.replace("|", "\\|")
        if len(text) > ONELINER_MAX_CHARS:
            text = text[: ONELINER_MAX_CHARS - 3].rstrip() + "..."
        return text
    return ""


def _rel_path(abs_path: str) -> str:
    return str(Path(abs_path).relative_to(KB_ROOT)).replace("\\", "/")


def _render_table(entries: list[Entry], type_name: str) -> list[str]:
    headers = SECTION_HEADERS_BY_TYPE.get(type_name, ["Overview"])
    lines: list[str] = []

    if type_name == "source":
        lines.append("| Slug | Status | Key Insight |")
        lines.append("|---|---|---|")
        for e in entries:
            oneliner = _extract_oneliner(e.body, headers)
            lines.append(
                f"| [{e.stem}]({_rel_path(e.path)}) | {e.status or '?'} | {oneliner} |"
            )
    else:
        lines.append("| Slug | Area | Status | Description |")
        lines.append("|---|---|---|---|")
        for e in entries:
            oneliner = _extract_oneliner(e.body, headers)
            area = ", ".join(e.area) if e.area else "-"
            lines.append(
                f"| [{e.stem}]({_rel_path(e.path)}) | {area} | {e.status or '?'} | {oneliner} |"
            )
    return lines


def build_index() -> str:
    entries = load_entries()
    by_type: dict[str, list[Entry]] = {}
    for e in entries.values():
        by_type.setdefault(e.type, []).append(e)
    for t in by_type:
        by_type[t].sort(key=lambda e: e.stem)

    total = len(entries)
    counts_str = ", ".join(
        f"{len(by_type[t])} {TYPE_LABEL[t].lower()}"
        for t in TYPE_ORDER
        if t in by_type
    )

    out: list[str] = [
        "# Modrn Mind KB — Index",
        "",
        f"_Auto-generated by `tooling/scripts/build-index.py`. Generated {date.today().isoformat()}._",
        "",
        f"**Total entries:** {total} ({counts_str})",
        "",
        "Use this index to find entries by name, status, or topical area. The full content of each entry is one click away. For programmatic search, use `tooling/scripts/kb_search.py`.",
        "",
        "---",
        "",
    ]

    for t in TYPE_ORDER:
        if t not in by_type:
            continue
        out.append(f"## {TYPE_LABEL[t]} ({len(by_type[t])})")
        out.append("")
        out.extend(_render_table(by_type[t], t))
        out.append("")

    return "\n".join(out)


def main() -> int:
    content = build_index()
    INDEX_PATH.write_text(content, encoding="utf-8")
    print(f"Wrote {INDEX_PATH} ({len(content):,} chars)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
